language: node_js

script:
  - yarn test

node_js:
  - '7'

cache:
  yarn: true
  directories:
    - node_modules

deploy:
  before_deploy: "npm version --patch"
  provider: npm
  email:
    secure: j4tYvUhw1yyuEKsYD/5loHS12uFs+O3q2rMaCX+W2DeGP1EVq4bpEGO5FDOnKQrdEsTBt7vg0NjWx3MgPWKzJNQ5wG3T3vXr1nxvgLi6ZI85eon8rZRCG6dyVCdxH7jT6FYRQ+tw2yF5TpuU4lI3oAF/XOy0qQCWgnndjkHsjQuAI6znyEom8yU/eezQpAIqxm3xDzoY8R0dD5TrJHDyoBEhZh2IUrJ2hCcLL0YMBysMIElvGfzJaqx66iPJjmEHNWytCgTXrcrxclWuV6/tPQhPRgrL3jh4ENd8+ZpGU9prZljWW/7yKNUUNHi9LqbmMgwiHzYdpPBkWqYsphz9HgsRQBvQRm9qxHw0FEzu2XEWDqpdBg5GX0HlaZ0y5HoqO0UWtIBhsV0CxaSLfXyJjHprFMrpMJnbvaf+WEJDsJys85P/jBB0wBIxsp2ezvPFTsL9fgQPsPgwtNOI+xwFIwJDey1OSX5UkEz/nk05ZJEkFuDdmiZp2I4Y6OslJW3ONaF6W7Y2XwWkFr4uaegtmf911mwV+RZpVy9wT9iQmanoQyanyf5WtswUJtfmUb0gqKotGwuZFm2PPqipUj/gb0VB6W6HFm71ewfZ5K0haATvaovPZB1STBGs68x5SjlTXT0tyNgLzyFU5bJ2CSSigIfkDE8YKp6bSCNa119L9xw=
  api_key:
    secure: nxu8YbDofiaKQPs9fxdvY1ERYLLZCTlUFDz0dYmtu541JDYu5bNTWsZaoLmsYEGa+pQ6SMlFFiiGH82ZJryyqlReFCrcGbC+FCBAgDMT10zuSl68kF6qe8ck8OjQySrGwsPGGmm3Qv3mHh4RbsAk37ujseDVSyQJg+cSdOKroFJf7bGTHME2tIFMPFq4Yl0Zi0KmAK3ItliVX9bAuKV6lVjAhYqyFoTbl7YqHAzowyH1FuEqPJy4fhwQ2lvsFqKHdr6Gy7CQNfilVY6bFwcfDct4ZAHCV3GqtAD81yZtEbbNG3DU9cH3HwkBKHzIShQOIqWY/WSpDU9JuKipz6JY++ri5/cZ2os6u0Z4c7g3vcah6dROJYs6Qd4DwT7956AeCz2qZg28hd0AH0Ymvzys6gAhCDRKWxtrOaZVpKCgottLD67GS+YwtYT6OgCPspil0cTtMR/riUqDc+XBsAmu14E57p8eWPx7kAjiE1sM6GcLLw0kt5oaS3Nq14LD8teXK6qvFsPkZF4psz8Fx5BhLV+rgM/ck67EKKKlGnt+278ZgNpMXzECuzotzNu1MCYIoOPaGvKKqSHqJYzIcWZc1hhJNu6X2hWFKD2UibxWm+TTNvku6A5N/SDYOI3KTuJlAEOLfR3ENZbSd//xdeGzCaAu63swJtWcMGL9rhw1wtE=
  on:
    branch: master
  skip_cleanup: true
